### PR TITLE
User Profile picture

### PR DESCRIPTION
**Pull request by XavierOlland**
Just a small add-on to add profile pictures to users.
To avoid errors :
- Add “pictures” folder to content
- Add "picture" to admin entry in database

Can be seen on http://zerokeyboard.com/blog

### CODE REVIEW

**Comment by dignajar** [comment]
Hi Xavier, I am changin the admin panel and other components because of this the branch is in conflicts. Thanks.

**Comment by XavierOlland** [comment]
OK let me know when I should update this and repull

**Comment by dignajar** [comment]
Implemented.

**Comment by XavierOlland** [comment]
Nice ! Keep the good work !

**Pull request closed without merging**
