### PR TITLE
Language: Improve Dutch translations

### PR DESCRIPTION
**Pull request by Joery**
- Add missing lines that were added to recent Bludit versions
- Correct the leading spacing
- Change the leading spacing from spaces to tabs
- Improve existing translated lines

I've used the English language file as example for the new lines and correct spacing.

### CODE REVIEW

**Comment by dignajar** [comment]
Hi,
there is an error on the line 221.

**Comment by Joery** [comment]
It's fixed now, I forgot a comma.

**Comment by Joery** [comment]
Added translations for the default plugins and theme.
Also fixed a small typo in the English Disqus plugin.

**Comment by dignajar** [comment]
Thanks!

**Pull request merged**
