### PR TITLE
Update to the latest version

### PR DESCRIPTION
**Pull request by 18jaguar18**
Update to version v0.7

### CODE REVIEW

**Comment by dignajar** [comment]
This branch has a conflict with the current files..

**Comment by 18jaguar18** [comment]
The problem is the location Bludit and not with the translation.
File  en_US.json copied and changed Locale settings causes the error.

http://i.imgur.com/AwGKWdZ.png

**Comment by 18jaguar18** [comment]
Indifferent what language I will not change the name of the month and the word user profile password.
Please add to language translation.

**Comment by kaaleth** [comment]
Stop use google translate before posting and making translation. What an id...

I wara od PluXML, skąd Ty się urwałeś dzieciak? -> http://forum.pluxml.org/viewtopic.php?id=2239

**Comment by 18jaguar18** [comment]
no comment

**Comment by dignajar** [comment]
Still in conflict this branch.

**Pull request closed without merging**
