### PR TITLE
bg_BG Update

### PR DESCRIPTION
**Pull request by Dipchikov**

### CODE REVIEW

**Comment by dignajar** [comment]
Hi, check the comments I made on the code.. thanks

**Comment by Dipchikov** [comment]
I don't understand what you mean. Please help me to fix the problem:(

**Comment by dignajar** [comment]
Hi,
this line
```$L->g('Current status')```

is equal to
```$L->g('current-status')```

**Comment by dignajar** [comment]
and why you add this "Disable the user", the value is incorrect for the input.

Status = Disabled / Enabled

**Comment by Dipchikov** [comment]
I am not shure how to explain but it is feature of the Bulgarian language. We use different words when we speek for a  peaple and options.

**Pull request closed without merging**
