### PR TITLE
Admin folder URL

### PR DESCRIPTION
**Pull request by kimkeown**
I am so pleased that I found Bludit! Its flat-file system is ideal, with intelligent organization, intuitive use, and theme customization far beyond that of many applications. And it's a fun program to use. 

One feature I am less than enthusiastic about is the easily-found and often publicly theme-linked Admin folder. I prefer a private login area when possible to help increase security and would not want a link to it from posted pages where it can be easily recorded by SEO bots.

Looking though the Admin code, it appears to be extremely well thought-out with a consistent use of definitions provided in the boot/init.php file. However, a variable was not defined for the Admin folder and the folder name string is used throughout the application.

The update I've made is to add a variable that would allow Users to change the name of the Admin folder to enable a more private login area. 24 files were updated to facilitate that ability, and replacing the admin string with a variable seemed in keeping with the rest of the well-defined code. 

It was an extensive undertaking and worked successfully in my initial use of the revisions that included admin panel login/logout, settings, new/updated users, adding/editing/deleting posts, adding/removing images, changing themes, activation/deactivation/content of plugins such as maintenance & about, and admin/editor roles. The revisions were used with different browsers and the email login tokens worked. 

In the volume of files to update, it's possible I missed something (be it a file, coding placement, concept, typo, etc.). I would appreciate your feedback and will be glad to make any additional revisions that may be needed to implement the renaming capability. 

Thank you! 
Kimberly

### CODE REVIEW

**Comment by dignajar** [comment]
Hi, I understand this problem, about the security, but passing a variable in all the Core of Bludit I don't like it. I will try to make something with a constant.

**Comment by kimkeown** [comment]
Would you please provide some insight as to your reason for not wanting to use the variable?

**Comment by anaggh** [comment]
Security through obscurity is not worth it and I think Bludit has bruteforce protection in its core.

**Comment by kimkeown** [comment]
​​​Your kind words and willingness to collaborate on this update were greatly appreciated!
It's inspiring to know the decision to reject a user-friendly upgrade was not based on a subjective whim.
Seriously...

It's fortunate that I do not have to rely on the '​thoughtful' assumptions of others that an application's brute-force protection is so impermeable the location of the file it protects should be advertised to everyone who visits the site. It's rather inconsiderate to expect users who want their keyword-rich websites searched to use a robots.text file that forbids SEO bots just to prevent the log-in link from being displayed, and does nothing to discourage casual hackers from attempting to defeat the brute-force protection out of curiosity and opportunity.

The willingness to deeply consider the welfare of those who use the program is heart-warming.

Thank you for your time.

**Comment by anaggh** [comment]
@kimkeown I hope I did'nt offend you in anyway. Everyone appreciates your contributions here. A determined hacker would find the admin path no matter what. `/bl-content/databases/security.php` is configurable. Perhaps setting a high `minutesBlocked` value and low `numberFailuresAllowed` value would increase the security even if the casual hacker has several rotating proxy IP's. Adding Google reCAPTCHA to the login form should further block most of the attacks.

I know the robots.txt does not serve the purpose for your intention but that's the least you could do to keep script kiddies at bay. The default `admin` directory name used is not safe, I agree but the goal should be to make it safe and not play the cat and mouse game.

I have tried renaming the `wp-admin` directory on a Wordpress installation in the past and it was completely pointless. It resulted in bots attacking on wp-login.php directly. Then I tried using htpasswd. Even that was attacked. In the end I had to whitelist my home IP on wp-login.php and /wp-admin/ restricting several files. I just said what I felt from experience. Just my 2 cents.

**Comment by dignajar** [comment]
@kimkeown, nobody tries to offend you, here we can talk about the implementations and get the best solution.

The admin panel has the metatags `<meta name="robots" content="noindex,nofollow">` this replace the robot.txt, or not ?

Regards
Diego

**Comment by kimkeown** [comment]
Thank you for the elaboration. The templates themselves have a link to the Admin panel on every page, and although robots.txt prevents bots who honor it from searching the linked page, it's visible and accessible to everyone who visits the website and advertises the site _has_ a login. The 'powered by' name and source code itself can easily be followed to that effect, and without doubt there are users who like the convenience of the link. However, it's as probable there are others who do not want its presence visible and do not know enough about editing a template to remove it. 

I realize folder obscurity is not a cure-all solution; yet it's a preventive measure that can be helpful and the user is able to decide what is worthwhile. With this application it did not seem to be too difficult to replace the folder name and provide that option. 

Learning more about constants, I understand the reason it would be preferred to a variable in such an instance as it's unalterable and global. Thus, changing the variable declaration to a define statement and replacing the same strings with it (minus the global references on function pages) would effect the folder rename in the same way the variable did. 

The validity of the update and whether or not to implement it is up to you as owners of the program, and your expertise and experience is rightfully the deciding factor in any revision. I merely offer the suggested modification and willingness to provide its implementation as a way of expressing my thanks for providing a nice flat-file application.

**Pull request closed without merging**
