### PR TITLE
Update to the latest version

### PR DESCRIPTION
**Pull request by 18jaguar18**

### CODE REVIEW

**Comment by kaaleth** [comment]
Wow, you stole my translation and changed copyright. Good job!

**Comment by 18jaguar18** [comment]
It was you who first stole my translation. 
Admin should know who made the first translation.

**Comment by kaaleth** [comment]
I made translate for nnibbleblog and bludit is continuation of diego's project. My file was made on English but you file is basen on mine. Moreover you changed hale low quality sobie please leave....

**Comment by 18jaguar18** [comment]
Bludot is an entirely different system than Nibbleblog.
My translation is of good quality, please you do not do clutter.

**Comment by dignajar** [comment]
Hi,
here is the commit history, https://github.com/dignajar/bludit/commits/master/languages/pl_PL.json

18jaguar18, it's the first who create the file.

I'm thinking you need to add both author, and colaborate eachother.

**Comment by kaaleth** [comment]
Thanks for meble this poor changes... Oh, I don't care I lost my time here. Good luck!

**Pull request merged**
