### PR TITLE
Google webmasters tools error "lastmod" date not valid

### PR DESCRIPTION
**Pull request by MichelePalmieri**
It solves the invalid date error

### CODE REVIEW

**Comment by dignajar** [comment]
The error is for a invalid date format ?

**Comment by acrox999** [comment]
I believe this is the issue that we've discussed before where old pages (before 1.0) do not get their dates properly generated in the sitemap. I thought this have already been fixed, @dignajar ?

This patch however, completely removes the date entry in the sitemap. I don't think that's an issue since date tags are optional, IIRC.

**Comment by MichelePalmieri** [comment]
example with error generated files

cattura11

**Comment by dignajar** [comment]
I think the best way is add the current date;

```
$lastmod	= $doc->createElement('lastmod', Date::current(SITEMAP_DATE_FORMAT));
```

**Comment by dignajar** [comment]
This issues is fixed. thanks

**Pull request closed without merging**
