### PR TITLE
Look for .htaccess only on Apache or LiteSpeed

### PR DESCRIPTION
**Pull request by alexandreteles**
Doesn't make any sense to look for a .htaccess file if bludit is running on other web server that isn't Apache or Litespeed. I've just placed a small verification to not generate errors if you try to install it using Nginx, for example, and the .htaccess file isn't in place.

### CODE REVIEW

**Comment by alexandreteles** [comment]
Can someone test it and provide feedback?

**Comment by dignajar** [comment]
Hi, and what happen if the webserver doesn't have the variable SERVER_SOFTWARE.

Regards

**Comment by alexandreteles** [comment]
Just pushed a commit to verify if the server has SERVER_SOFTWARE defined. If the variable isn't defined it still doesn't make sense to ask for the .htaccess as it definitively isn't Apache or LiteSpeed (or is a very strange self compiled version of those softwares).

**Comment by dignajar** [comment]
Hi, some web server packages, such as XAMP and similar has Apache and the variable is not defined, there is a lot of users who check Bludit on his own servers. I'm looking another solution.

**Comment by dignajar** [comment]
What about this code..

`if( !file_exists(PATH_ROOT.'.htaccess') ) {
	
	$htaccessWebservers = array('apache', 'litespeed');

	if ( !isset($_SERVER['SERVER_SOFTWARE']) || in_array($_SERVER['SERVER_SOFTWARE'], $htaccessWebservers) ) {
		echo 'FILE MISSING';
	}
}
`

**Comment by alexandreteles** [comment]
@dignajar I didn't know that XAMP doesn't define it. Well, I actually like your solution, I think it should work.

**Comment by dignajar** [comment]
I used your code..

```
	// Check .htaccess file for different webservers
	if( !file_exists(PATH_ROOT.'.htaccess') ) {

		if (	!isset($_SERVER['SERVER_SOFTWARE']) ||
			stripos($_SERVER['SERVER_SOFTWARE'], 'Apache') !== false ||
			stripos($_SERVER['SERVER_SOFTWARE'], 'LiteSpeed') !== false
		) {
			$errorText = 'Missing file, upload the file .htaccess (ERR_201)';
			error_log($errorText, 0);

			$tmp['title'] = 'File .htaccess';
			$tmp['errorText'] = $errorText;
			array_push($stdOut, $tmp);

		}
	}
```

**Pull request closed without merging**
