### PR TITLE
Fix double string + update french + Call hooks php/template

### PR DESCRIPTION
**Pull request by Fred89**

### CODE REVIEW

**Comment by dignajar** [comment]
If you can, make 1 pull request for each issues, because if I merge your pull request I will replace all files and some files are incorrect like the en_US file.

**Comment by Fred89** [comment]
Only those with write access to this repository can merge pull requests.

**Comment by Fred89** [comment]
I have a conflicts with this  branch :(

**Comment by dignajar** [comment]
Yeap I see this alert "This branch has conflicts that must be resolved" ?

From your recomendation I add this for debug mode, https://github.com/dignajar/bludit/blob/master/kernel/boot/init.php

**Comment by dignajar** [comment]
Done, I uploaded your french dictionary.

**Comment by Fred89** [comment]
Thank Diego, do you have a hangout pseudo or email ?
If you have please send me in MP on Bludit forum.

**Pull request closed without merging**
